apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argo-workflows
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/argo-workflows
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: argo-workflows
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
