apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jupyter
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/jupyter
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: jupyter
  wait: true
  timeout: 10m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
