apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mlflow
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/mlflow
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: mlflow
  wait: true
  timeout: 10m
  decryption:
      provider: sops
      secretRef: 
        name: sops-age