apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  interval: 10m
  path: ./deploy/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

  dependsOn:
    - name: postgres-operator

  decryption:
    provider: sops
    secretRef:
      name: sops-age
